### ISSUE TITLE
篩選器板面太大

### ISSUE THREAD

**Issue by renddiyeh** [relabcc/east-spring#16]

**Comment by renddiyeh** [comment]
now better?
![image](https://cloud.githubusercontent.com/assets/3462696/25087215/d8e468ba-239f-11e7-8092-4cea689cbd67.png)

**Comment by Relab-Mike** [comment]
手機版有變小，不過電腦版的還是一樣欸？

**Comment by renddiyeh** [comment]
![image](https://cloud.githubusercontent.com/assets/3462696/25112831/53a7d0b0-2426-11e7-803c-83c8ec7c32ad.png)
電腦兒
