### ISSUE TITLE
電腦版大象會遮住推進你的尤加利

### ISSUE THREAD

**Issue by Relab-Mike** [relabcc/east-spring#27]
手機版不會遮住
但剛剛在用電腦滑的時候發現大象還是會遮到
![2017-04-18 1 29 06](https://cloud.githubusercontent.com/assets/27659279/25097411/fff77ca8-23d6-11e7-917d-731bd35fb8d1.png)

**Comment by renddiyeh** [comment]
在不同解析度下可能會出現，要再想辦法
