### ISSUE TITLE
探險收益－總回報range修改

### ISSUE THREAD

**Issue by Relab-Mike** [relabcc/east-spring#4]
改為
4%以下、4-8%、8-12%、12-16%、16%以上

**Comment by renddiyeh** [comment]
但是篩不出結果? @Relab-Mike 
![image](https://cloud.githubusercontent.com/assets/3462696/25081895/a98fa446-237f-11e7-93a5-4cb0f4890085.png)

**Comment by renddiyeh** [comment]
#11
