### ISSUE TITLE
小細節

### ISSUE THREAD

**Issue by Relab-Mike** [relabcc/east-spring#49]
![2017-04-21 11 38 02](https://cloud.githubusercontent.com/assets/27659279/25285083/aa87a80c-26eb-11e7-8d61-c3711f1c689a.png)

**Comment by renddiyeh** [comment]
沒有多括弧阿?
![image](https://cloud.githubusercontent.com/assets/3462696/25313144/845c373a-285b-11e7-9d22-7b5736164807.png)

**Comment by Relab-Mike** [comment]
可是現在網站進不去我看不到耶
