### ISSUE TITLE
電腦版的bar 要加「多圓收益好實在」

### ISSUE THREAD

**Issue by Relab-Mike** [relabcc/east-spring#56]
真的很腦 但她打電話來有靠腰這件事

**Comment by renddiyeh** [comment]
那我可以加星星嗎
比較有感覺
![image](https://cloud.githubusercontent.com/assets/3462696/25313572/96b9cff2-2863-11e7-95a1-caad8d99a9bc.png)
![image](https://cloud.githubusercontent.com/assets/3462696/25313584/c769484e-2863-11e7-8552-9ac1f3867708.png)

**Comment by Relab-Mike** [comment]
我覺得可以欸應該沒關係
