### ISSUE TITLE
首頁警語

### ISSUE THREAD

**Issue by Relab-Mike** [relabcc/east-spring#6]

**Comment by renddiyeh** [comment]
![image](https://cloud.githubusercontent.com/assets/3462696/25173504/f125442a-2526-11e7-9802-bc5ea8430bd0.png)

**Comment by renddiyeh** [comment]
![image](https://cloud.githubusercontent.com/assets/3462696/25173510/fe238d44-2526-11e7-82ba-e192c9677378.png)
