### ISSUE TITLE
總回報

### ISSUE THREAD

**Issue by Relab-Mike** [relabcc/east-spring#62]
現在總回報是透明顯示如果選了股票才會浮出，瀚亞的ＰＰＴ把透明圈起來 
不知道他們想表達什麼，可能是不喜歡（？
看要不要不透明顯示

**Comment by renddiyeh** [comment]
齁!
這樣是要怎麼改啦

**Comment by Relab-Mike** [comment]
登愣
因為他就真的只有圈起來
改成別透明顯示好了
