### ISSUE TITLE
首頁下方小地圖

### ISSUE THREAD

**Issue by Relab-Mike** [relabcc/east-spring#68]
早上瀚亞有提到那個地圖icon不是很明顯
也不知道下方的地圖可以滑動可以點
有沒有可能把小地圖icon拿掉 改成「快速抵達」四個字？

**Comment by renddiyeh** [comment]
我覺得要測測看耶
因為隨著滑動，下面本來就會動
然後如果首頁直接點了某一區
下面的移動也會很劇烈
應該是會注意到啦

但重點是，改成快速抵達，太直白了，降低格調
我不喜歡哈哈哈
